### ISSUE TITLE
Reunión de Comunicación (Grupo 1 y 2)

### ISSUE THREAD

**Issue by edubsteep** [InnosoftDaysPresidencia/Comunicacion#3]
Fecha: 17/10/2017 a las 9:30
Orden de la reunión:
-Establecer flujos de comunicación.
-Elegir logo y eslogan.
-Elaborar y aprobar dossier de comunicación

**Comment by juahueceb1** [comment]
La Presidencia de la jornada ha dado su visto bueno al dossier después de cambiar algunos puntos: introducción, tema principal y sobre nosotros. La Presidencia se encargará de enviar el dossier a todos los comités.

**Comment by albgomceb** [comment]
He subido el acta de reunión en el commit 5baedc47ac7275be97ecea52a3afa7ad8b9f0e12. Cierro el issue.
